/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\particles.glb 
*/

import React, { useRef, useMemo, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

// Composant pour une particule individuelle avec effet brillant animé et mouvement de flottement
function SparklingParticle({ position, delay = 0, geometry, baseMaterial, movementOffset = 0, size = 1, brightness = 1 }) {
  const meshRef = useRef()
  const initialPosition = useMemo(() => new THREE.Vector3(...position), [position])

  // Cloner le material : émission = blanc pur, seule l'intensité varie (blanc lumineux → noir)
  const material = useMemo(() => {
    if (!baseMaterial) return null
    const cloned = baseMaterial.clone()
    
    // Toujours blanc pur pour l'émission : pas de gris, juste intensité qui baisse vers 0
    cloned.emissive = new THREE.Color(0xffffff)
    
    if (cloned.emissiveIntensity !== undefined) {
      cloned.emissiveIntensity = 0
    }
    
    return cloned
  }, [baseMaterial])

  useFrame((state) => {
    if (!meshRef.current || !material) return
    
    const time = state.clock.elapsedTime
    
    // Effet Color Ramp : brillance qui varie, mais étoiles toujours visibles (pas de noir)
    const sparkleTime = time * 0.05 + delay
    const factor = (Math.sin(sparkleTime) + 1) / 2 // 0 à 1
    
    // Étoiles toujours visibles : luminosité min 30%, max 100% (basé sur brightness)
    const minEmission = 1.0 * brightness // Toujours visible
    const maxEmission = 3.5 * brightness // Pic de brillance
    const emissionIntensity = minEmission + (maxEmission - minEmission) * factor
    
    if (material.emissiveIntensity !== undefined) {
      material.emissiveIntensity = emissionIntensity
    }
    
    // Mouvement de flottement TRÈS lent
    const floatSpeed = 0.01 + movementOffset * 0.01 // 4x plus lent
    const floatAmount = 0.01 * size // Amplitude réduite
    
    const floatX = Math.sin(time * floatSpeed + movementOffset) * floatAmount
    const floatY = Math.cos(time * floatSpeed * 0.8 + movementOffset) * floatAmount
    const floatZ = Math.sin(time * floatSpeed * 0.6 + movementOffset) * floatAmount * 0.5
    
    meshRef.current.position.set(
      initialPosition.x + floatX,
      initialPosition.y + floatY,
      initialPosition.z + floatZ
    )
    
    // Rotation très lente, variable par étoile
    meshRef.current.rotation.x += 0.0001 * size
    meshRef.current.rotation.y += 0.00015 * size
  })

  if (!material) return null

  return (
    <mesh
      ref={meshRef}
      geometry={geometry}
      position={initialPosition}
      scale={size}
      material={material}
    />
  )
}

export function Model({ maxParticles = 200, groupRef, ...props }) {
  const { nodes, materials } = useGLTF('/particles.glb')
  const internalGroupRef = useRef()
  
  // Exposer la ref au parent si fournie
  useEffect(() => {
    if (groupRef && internalGroupRef.current) {
      if (typeof groupRef === 'function') {
        groupRef(internalGroupRef.current)
      } else {
        groupRef.current = internalGroupRef.current
      }
    }
  }, [groupRef])
  
  // Créer un nuage d'étoiles : plus de particules, tailles variées, répartition en nuage
  const particles = useMemo(() => {
    const count = maxParticles
    return Array.from({ length: count }, (_, i) => {
      // Distribution en forme de nuage (plus dense au centre)
      const radius = Math.random() * 15 + 5 // Rayon entre 5 et 20
      const theta = Math.random() * Math.PI * 2
      const phi = Math.acos(2 * Math.random() - 1) // Distribution sphérique uniforme
      
      const x = radius * Math.sin(phi) * Math.cos(theta)
      const y = radius * Math.sin(phi) * Math.sin(theta)
      const z = radius * Math.cos(phi)
      
      // Variation de taille : quelques grosses étoiles, beaucoup de petites
      const sizeRandom = Math.random()
      const size = sizeRandom > 0.9 ? 12 + Math.random() * 8 : // 10% très grosses
                   sizeRandom > 0.7 ? 8 + Math.random() * 4 :  // 20% grosses
                   5 + Math.random() * 3                       // 70% petites
      
      // Luminosité variable : les grosses étoiles sont plus brillantes
      const brightness = 0.4 + (size / 20) * 0.6 // Plus l'étoile est grosse, plus elle peut être brillante
      
      return {
        position: [x, y, z],
        delay: Math.random() * Math.PI * 2,
        movementOffset: Math.random() * Math.PI * 2,
        size,
        brightness,
      }
    })
  }, [maxParticles])

  return (
    <group ref={internalGroupRef} {...props} dispose={null}>
      {particles.map((particle, i) => (
        <SparklingParticle
          key={i}
          position={particle.position}
          delay={particle.delay}
          movementOffset={particle.movementOffset}
          size={particle.size}
          brightness={particle.brightness}
          geometry={nodes.Icosphere.geometry}
          baseMaterial={materials.Mat_Etoile}
        />
      ))}
    </group>
  )
}

useGLTF.preload('/particles.glb')
